services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
language: go
go:
    - 1.7
script: 
    - cp ./config.travis.yml ./config.yml
    - go test -p 1 ./...
