development:
  database:
    url: mongodb://localhost:27017/tuna_timer_prod
development:
  database:
    url: mongodb://localhost:27017/tuna_timer_dev
test:
  database:
    url: mongodb://localhost:27017/tuna_timer_test

