production:
  database:
    url: mongodb://localhost:27017/tuna_timer_prod
  slack:
    client_id: ""
    client_secret: ""
    verification_token: ""
  origin:
    url: ""
development:
  database:
    url: mongodb://localhost:27017/tuna_timer_dev
  slack:
    client_id: ""
    client_secret: ""
    verification_token: ""
  origin:
    url: "http://localhost:4200"
test:
  database:
    url: mongodb://localhost:27017/tuna_timer_test
  slack:
    client_id: ""
    client_secret: ""
    verification_token: ""
  origin:
    url: "http://localhost:4200"
