version: '2'
services:
  app:
    image: pavlikus/slack-time:latest
    environment:
      SLACK_TIME_ENV: 'production'
      DATABASE_URL: 'mongodb://db:27017/tuna_timer'
    depends_on:
      - db
    entrypoint: ['/wait-for-it.sh', 'db:27017', '--strict', '--', '/slack-time-linux-amd64']
  db:
    image: mongo:3.2
  proxy:
    image: abiosoft/caddy
    ports:
      - "9090:9090"
    volumes:
      - ./Caddyfile:/etc/Caddyfile
    depends_on:
      - app
